# Generated by Django 6.0 on 2026-01-22 02:40

import django.core.validators
import pokemon_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('move_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, validators=[pokemon_app.validators.validate_name])),
                ('level', models.IntegerField(default=1)),
                ('date_encountered', models.DateField(auto_now_add=True)),
                ('captured', models.BooleanField()),
                ('description', models.TextField(default='Unkown', validators=[django.core.validators.MinLengthValidator(5), django.core.validators.MaxLengthValidator(150)])),
                ('moves', models.ManyToManyField(to='move_app.move')),
            ],
        ),
    ]
